import {centralDate,shiftDate,type BroadcastData,type Game} from './model';
const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const text=(id:string,value:string)=>{el(id).textContent=value;};
const channel=el('channel');
function fit(){const scale=Math.min(innerWidth/1920,innerHeight/1080);channel.style.transform=`scale(${scale})`;channel.style.left=`${(innerWidth-1920*scale)/2}px`;channel.style.top=`${(innerHeight-1080*scale)/2}px`;}
addEventListener('resize',fit);fit();
let data:BroadcastData|null=null,storyIndex=0,boardIndex=0,railIndex=0,tickerIndex=0,rankingIndex=0,slide=0,slideStart=performance.now();
let scoreAnimation:Animation|undefined,newsAnimation:Animation|undefined;
const dateLabel=(date:string)=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(date.slice(0,10)+'T12:00:00Z'));
const displayTime=(time:string)=>time.replace(/\s*·\s*source time\b/gi,'').trim();
const displaySource=(source:string)=>source.split(' · ')[0];
function safeUrl(value:string){try{const u=new URL(value,location.origin);return u.protocol==='https:'||u.origin===location.origin?u.href:null;}catch{return null;}}
function image(id:string,url:string|null){const img=el<HTMLImageElement>(id);if(!url||!safeUrl(url)){img.removeAttribute('src');img.style.visibility='hidden';return;}if(img.getAttribute('src')!==url){img.style.visibility='hidden';img.onload=()=>{img.style.visibility='visible';};img.onerror=()=>{img.style.visibility='hidden';};img.src=url;}}
function available(kind:'final'|'scheduled'|'result'|'in-progress'):Game[]{const today=centralDate();const games=(data?.games||[]).map(g=>({...g,stale:g.stale||(g.sourceId.startsWith('scoreboard-')&&g.date===today&&Date.now()-Date.parse(g.observedAt)>900000)})).filter(g=>!g.conflict&&g.status===kind&&(kind!=='in-progress'||Date.now()-Date.parse(g.observedAt)<3600000)&&g.date>=shiftDate(today,-7)&&(kind!=='scheduled'||g.date>=today)).sort((a,b)=>kind!=='scheduled'?b.date.localeCompare(a.date):a.date.localeCompare(b.date));
  // Give each level regular airtime even when high-school records greatly outnumber college games.
  const groups=['High school','JUCO','College'].map(level=>games.filter(g=>g.level===level));const mixed:Game[]=[];for(let i=0;i<Math.max(...groups.map(g=>g.length),0);i++)for(const group of groups)if(group[i])mixed.push(group[i]);return mixed;}
function card(game:Game){const div=document.createElement('div');div.className='game';
  const meta=document.createElement('div');meta.className='game-meta';meta.textContent=`${game.level} · ${game.sport} · ${dateLabel(game.date)}`;div.append(meta);
  game.teams.forEach((name,i)=>{const row=document.createElement('div');row.className='team';const n=document.createElement('span');n.textContent=name;const s=document.createElement('b');s.textContent=(game.status==='final'||game.status==='in-progress')&&game.scores?String(game.scores[i]):'';row.append(n,s);div.append(row);});
  const foot=document.createElement('div');foot.className='game-foot';
  foot.textContent=`${game.stale?'DELAYED · ':''}${game.status==='in-progress'?(game.scores?'LIVE':'LIVE · SCORE PENDING'):game.status==='final'?'FINAL':game.status==='result'?game.result||'Results':displayTime(game.time)} · ${displaySource(game.source)}`;div.append(foot);return div;
}
function cards(target:string,games:Game[],message:string){const root=el(target);root.replaceChildren(...games.map(card));if(!games.length){const p=document.createElement('p');p.className='empty';p.textContent=message;root.append(p);}}
function boardKinds(){const list=(['in-progress','final','scheduled','result'] as const).filter(k=>available(k).length);return list.length?list:['scheduled'] as const;}
function page<T>(list:T[],index:number,size:number){if(!list.length)return [];return list.slice((index%Math.ceil(list.length/size))*size,(index%Math.ceil(list.length/size))*size+size);}
function showSlide(){
  const rankingGroups=(data?.rankings||[]).map(r=>['Overall',...new Set(r.entries.map(e=>e.classification))].flatMap(group=>{const rows=r.entries.filter(e=>group==='Overall'||e.classification===group).slice(0,10);return [0,5].filter(start=>start<rows.length).map(start=>({ranking:r,group,start,rows:rows.slice(start,start+5)}));}));
  const rankingPages=Array.from({length:Math.max(0,...rankingGroups.map(g=>g.length))},(_,i)=>rankingGroups.flatMap(g=>g[i]?[g[i]]:[])).flat();
  const showRanking=slide%6===5&&rankingPages.length>0,showBoard=slide%3===2&&!showRanking;el('story').hidden=showBoard||showRanking;el('scoreboard').hidden=!showBoard;el('rankings').hidden=!showRanking;
  if(showRanking){const p=rankingPages[rankingIndex++%rankingPages.length],r=p.ranking;text('ranking-title',`${r.sport} · ${p.group==='Overall'?'Statewide':p.group==='Private'?'Private':'Class '+p.group}`);text('ranking-subtitle',`${r.source} · Published ${dateLabel(r.publishedAt)}`);text('ranking-footer',`${new URL(r.sourceUrl).hostname.replace(/^www\./,'')}`);el('ranking-rows').replaceChildren(...p.rows.map((entry,i)=>{const row=document.createElement('div');row.className='ranking-row';const rank=document.createElement('b');rank.textContent=String(p.group==='Overall'?entry.rank:p.start+i+1);const team=document.createElement('div');const name=document.createElement('strong');name.textContent=entry.team;const meta=document.createElement('small');meta.textContent=`${entry.classification} · State #${entry.rank}`;team.append(name,meta);const record=document.createElement('span');record.textContent=entry.record;const rating=document.createElement('b');rating.textContent=entry.rating.toFixed(1);row.append(rank,team,record,rating);return row;}));}
  if(showBoard){const kinds=boardKinds(),kind=kinds[boardIndex%kinds.length];const games=available(kind);text('board-title',kind==='in-progress'?'Games in progress':kind==='final'?'Final scores':kind==='result'?'Around the meets':'Coming up');text('board-subtitle',kind==='in-progress'?'Reported scores · Across Mississippi':kind==='final'?'Around Mississippi':kind==='result'?'Track, field and more':'Upcoming games');cards('board-games',page(games,Math.floor(boardIndex/kinds.length),6),'Your state. Your teams.');boardIndex++;}
  else if(!showRanking&&data?.stories.length){const s=data.stories[storyIndex%data.stories.length];image('story-image',s.image);text('headline',s.title);text('story-date',dateLabel(s.publishedAt));storyIndex++;}
  slideStart=performance.now();slide++;
}
function updateRail(){const kinds=boardKinds().filter(k=>k!=='result'),kind=kinds[railIndex%kinds.length]??'scheduled',games=available(kind);text('rail-title',kind==='in-progress'?'IN PROGRESS':kind==='scheduled'?'UP NEXT':'LATEST FINALS');cards('rail-games',page(games,Math.floor(railIndex/Math.max(1,kinds.length)),2),'Your state. Your teams.');railIndex++;}
function crawl(id:string,animation:Animation|undefined,speed:number,iterations=Infinity){animation?.cancel();const node=el(id),width=node.scrollWidth,start=node.parentElement!.clientWidth;return node.animate([{transform:`translateX(${start}px)`},{transform:`translateX(-${width}px)`}],{duration:(width+start)/speed*1000,iterations});}
function updateTickers(){
  const kinds=boardKinds(),kind=kinds[tickerIndex%kinds.length];const games=available(kind);const root=el('score-ticker');root.replaceChildren();text('ticker-label',kind==='in-progress'?'LIVE':kind==='final'?'FINALS':kind==='result'?'RESULTS':'UP NEXT');
  for(const g of page(games,Math.floor(tickerIndex/kinds.length),6)){const span=document.createElement('span');span.className='ticker-item';const meta=document.createElement('small');meta.textContent=`${g.sport.toUpperCase()} · ${dateLabel(g.date)} · ${displaySource(g.source)}`;span.append(meta,document.createTextNode((g.status==='final'||g.status==='in-progress')&&g.scores?`${g.teams[0]} ${g.scores[0]} — ${g.teams[1]} ${g.scores[1]} · ${g.stale?'DELAYED':g.status==='in-progress'?'LIVE':'FINAL'}`:`${g.teams.join(g.event?' · ':' vs ')} · ${g.stale?'DELAYED · ':''}${g.status==='in-progress'?'LIVE · SCORE PENDING':g.status==='result'?g.result:displayTime(g.time)}`));root.append(span);}
  if(!root.childNodes.length)root.textContent='Mississippi Sports Group • Your state. Your teams.';
  scoreAnimation=crawl('score-ticker',scoreAnimation,95,1);void scoreAnimation.finished.then(updateTickers).catch(()=>{});tickerIndex++;
  const news=(data?.stories||[]).map(s=>s.title).join('     •     ')||'Sports Mississippi • Your state. Your teams.';if(el('news-ticker').textContent!==news||!newsAnimation){text('news-ticker',news);newsAnimation=crawl('news-ticker',newsAnimation,80);}
}
let received=false;
async function refresh(){try{const r=await fetch('/api/broadcast',{cache:'no-store',signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error('Unavailable');const value=await r.json();if(!Array.isArray(value.games)||!Array.isArray(value.sources)||!Array.isArray(value.stories))throw new Error('Invalid snapshot');data=value;try{localStorage.setItem('ms-broadcast-last-good',JSON.stringify(value));}catch{}if(!received){showSlide();updateRail();updateTickers();received=true;}}catch{/* Keep the current broadcast through a temporary feed interruption. */}}
try{const cached=JSON.parse(localStorage.getItem('ms-broadcast-last-good')||'null');if(cached&&Array.isArray(cached.games)&&Date.now()-Date.parse(cached.generatedAt)<86400000){data=cached;showSlide();updateRail();updateTickers();}}catch{}
void refresh();setInterval(()=>void refresh(),60000);setInterval(showSlide,14000);setInterval(updateRail,18000);
setInterval(()=>{const now=new Date();text('clock',new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',hour:'numeric',minute:'2-digit'}).format(now));text('today',new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',weekday:'short',month:'short',day:'numeric'}).format(now).toUpperCase()+' · CT');el('progress-bar').style.transform=`scaleX(${Math.min(1,(performance.now()-slideStart)/14000)})`;},250);
interface Sponsor {name:string;image?:string;headline?:string;phone?:string;fullscreenImage?:string;placements:('sidebar'|'fullscreen')[];active:boolean;startsAt?:string;endsAt?:string;}
interface SponsorConfig {sidebarSeconds:number;fullscreenEverySeconds:number;fullscreenSeconds:number;sponsors:Sponsor[];}
let config:SponsorConfig={sidebarSeconds:20,fullscreenEverySeconds:900,fullscreenSeconds:15,sponsors:[]},adIndex=0,fullIndex=0,lastSidebar=0,lastFull=Date.now(),fullUntil=0;
function activeAds(placement:'sidebar'|'fullscreen'){return config.sponsors.filter(s=>s.active&&s.placements?.includes(placement)&&((s.image&&safeUrl(s.image))||s.headline)&&(!s.startsAt||Date.parse(s.startsAt)<=Date.now())&&(!s.endsAt||Date.parse(s.endsAt)>Date.now()));}
async function sponsors(){try{const r=await fetch('/broadcast-sponsors.json',{cache:'no-store',signal:AbortSignal.timeout(10000)});if(!r.ok)return;const c=await r.json();if(Array.isArray(c.sponsors))config={sponsors:c.sponsors,sidebarSeconds:Math.max(5,Number(c.sidebarSeconds)||20),fullscreenEverySeconds:Math.max(60,Number(c.fullscreenEverySeconds)||900),fullscreenSeconds:Math.min(60,Math.max(5,Number(c.fullscreenSeconds)||15))};}catch{}}
void sponsors();setInterval(()=>void sponsors(),60000);
setInterval(()=>{const now=Date.now();if(now-lastSidebar>config.sidebarSeconds*1000){const list=activeAds('sidebar'),s=list[adIndex++%list.length];el('sponsor-image').hidden=!s?.image;el('sponsor-house').hidden=!!s?.image;text('sponsor-name',s?.image?s.name:'');text('house-title',s?.headline||'Your ad here');text('house-phone',s?.phone||'662-576-1554');if(s?.image)image('sponsor-image',s.image);lastSidebar=now;}
  if(now-lastFull>config.fullscreenEverySeconds*1000){const list=activeAds('fullscreen'),s=list[fullIndex++%list.length];if(s){el('full-image').hidden=!s.image;el('full-house').hidden=!!s.image;if(s.image)image('full-image',s.fullscreenImage||s.image);text('full-phone',s.phone||'662-576-1554');text('full-name',s.image?s.name:'');fullUntil=now+config.fullscreenSeconds*1000;}lastFull=now;}el('sponsor-full').hidden=now>=fullUntil;
},1000);
