import type {Source} from './model';
export const SOURCES: Source[] = [
  {id:'sportsmississippi',name:'Sports Mississippi',url:'https://sportsmississippi.com/wp-json/wp/v2/posts?per_page=20&_embed',kind:'wordpress',intervalMinutes:10,note:'Featured images and headlines; articles are not automatically treated as official scores.'},
  ...[['cc','Cross country'],['indoor','Indoor track'],['outdoor','Outdoor track']].map(([season,sport]):Source=>({id:'milesplit-'+season,name:'MileSplit MS · '+sport,url:`https://ms.milesplit.com/calendar?season=${season}&level=hs`,kind:'milesplit',level:'High school',sport,intervalMinutes:720,note:'Public Mississippi high-school meet calendar and links to posted results. Mixed HS/MS meets included as meets; elementary/MS-only events excluded. Individual paid results are not imported.'})),
  ...[
    ['football','Football'],['volleyball','Girls volleyball'],['basketball','Boys basketball'],['basketball/girls','Girls basketball'],
    ['baseball','Baseball'],['softball','Softball'],['soccer','Boys soccer'],['soccer/girls','Girls soccer']
  ].map(([path,sport]):Source=>({id:'maxpreps-'+path.replaceAll('/','-'),name:'MaxPreps · '+sport,url:`https://www.maxpreps.com/ms/${path}/scores/`,kind:'maxpreps',level:'High school',sport,intervalMinutes:720,note:'Mississippi varsity scoreboard; source-reported finals. Includes MHSAA and listed MAIS teams. Missing submissions remain gaps; not a licensed live feed.'})),
  ...[['football','Football','fbscores1.php'],['softball','Softball','fastpitchscores1.php'],['baseball','Baseball','basescores1.php'],['boys-basketball','Boys basketball','baskscores2.php'],['girls-basketball','Girls basketball','baskscores1.php'],['boys-soccer','Boys soccer','soccscores2.php'],['girls-soccer','Girls soccer','soccscores1.php']].map(([id,sport,file]):Source=>({id:'mais-'+id,name:'MAIS · '+sport,url:'https://home.msais.org/scoreboard/'+file,kind:'mais',level:'High school',sport,intervalMinutes:720,note:'Official submitted varsity/A-team finals. Includes MAIS member schools outside Mississippi; schedules supplemented by MaxPreps where listed.'})),
  ...[['volleyball','Girls volleyball','vbscores1.php'],['outdoor-track','Boys/girls outdoor track','trackoutresults1.php'],['indoor-track','Boys/girls indoor track','trackinresults1.php'],['cross-country','Boys/girls cross country','crossresults1.php'],['swimming','Boys/girls swimming','swimresults1.php'],['golf','Boys/girls golf','golfresults1.php'],['tennis','Boys/girls tennis','tennisresults1.php']].map(([id,sport,file]):Source=>({id:'mais-'+id,name:'MAIS · '+sport,url:'https://home.msais.org/scoreboard/'+file,kind:'mais-monitor',level:'High school',sport,intervalMinutes:720,note:'Monitored official result page. Published meet documents/set scores need validation before structured results can air; zero records does not mean no competition.'})),
  {id:'maccc',name:'MACCC · All-sport composite',url:'https://www.macccathletics.com/composite',kind:'maccc',level:'JUCO',intervalMinutes:720,note:'Official conference schedule/results. Team meets without two numeric scores are not labeled head-to-head finals.'},
  ...[
    ['olemiss','Ole Miss','olemisssports.com'],['state','Mississippi State','hailstate.com'],['usm','Southern Miss','southernmiss.com'],
    ['jsu','Jackson State','gojsutigers.com'],['alcorn','Alcorn State','alcornsports.com'],['mvsu','Mississippi Valley State','mvsusports.com'],
    ['delta','Delta State','gostatesmen.com'],['mc','Mississippi Christian','gochoctaws.com'],['millsaps','Millsaps','gomajors.com'],
    ['bmc','Blue Mountain Christian','www.bmcusports.com'],['carey','William Carey','careyathletics.com'],['belhaven','Belhaven','blazers.belhaven.edu'],['muw','Mississippi University for Women','owlsathletics.com']
  ].map(([id,school,host]):Source=>({id,name:school+' · Official athletics',url:`https://${host}/calendar`,kind:'calendar',level:'College',school,intervalMinutes:720,note:'Official all-sport calendar: schedules, explicit W/L/T finals and separately labeled published meet results. Reporting depends on school updates.'})),
  ...[['rust','Rust','rustathletics.com'],['tougaloo','Tougaloo','tougaloobulldogs.com']].map(([id,school,host]):Source=>({id,name:school+' · Official athletics',url:`https://${host}/composite`,kind:'maccc',level:'College',school,intervalMinutes:720,note:'Official all-sport composite. Empty dates and missing school updates are shown as coverage gaps.'}))
];
export const GAPS = [
  {name:'MHSAA meet and individual results',url:'https://www.misshsaa.com/',note:'MileSplit MS supplies public HS race meets and posted-result links. Individual athlete times, swimming, golf, tennis, powerlifting, bowling, wrestling, esports and other non-scoreboard results still need sport-specific adapters. MHSAA links to MaxPreps for scoreboards.'},
  {name:'MAIS volleyball and meet results',url:'https://home.msais.org/scoreboard/bigscores.html',note:'All published official score/result pages are monitored. Volleyball has set-level records; track, cross country, swimming, golf and tennis pages returned no results during verification. Upcoming games rely on MaxPreps listings and are not complete.'},
  {name:'MAIS archery and cheer/dance',url:'https://home.msais.org/test2/code/athletics/handbook_entire.php',note:'In scope for boys/girls varsity coverage. No structured public schedule/results feed verified yet; needs official championship or school feeds.'},
  {name:'NJCAA national events / missing JUCO submissions',url:'https://www.njcaa.org/',note:'MACCC composite is connected. National championships, individual results and events absent from MACCC need supplemental school/NJCAA adapters.'},
  {name:'Four-year school reporting gaps',url:'https://www.ncaa.com/schools',note:'All 15 identified Mississippi NCAA/NAIA four-year schools are configured. Source health below reports actual successful collection. Meet results retain source wording; numeric head-to-head finals require explicit W/L/T and two scores. Schools may omit or delay events.'}
  ,{name:'Rust current calendar missing',url:'https://rustathletics.com/composite',note:'Official composite returned no current events while navigation linked older seasons. Rust remains in scope, but current coverage requires an updated school or conference feed.'}
];
