import test from 'node:test';
import assert from 'node:assert/strict';
import {parseMaxPreps,FeedCollector} from '../lib/providers.mjs';
import {filterGames,centralDate,deduplicate,validDate} from '../public/shared.mjs';
const sport={key:'volleyball',label:'Volleyball',path:'volleyball'},date='2026-10-06';
function card({id='a',path='/ms/volleyball/match/alcorn-central-vs-kossuth/10-6-2026/',names=['Alcorn Central','Kossuth'],scores=[null,null],detail='5:30p',state='pregame',live='0'}={}){
  return `<li data-contest-id="${id}"><div class="contest-box-item" data-contest-state="${state}" data-contest-live="${live}"><a class="c-c" href="https://www.maxpreps.com${path}?c=${id}"><ul class="teams">${names.map((name,i)=>`<li><div class="record">10-3</div>${scores[i]!==null?`<div class="score">${scores[i]}</div>`:''}<div class="name"><span class="rank">(#12)</span>${name}</div></li>`).join('')}</ul><div class="details">${detail}</div></a></div></li>`;
}
test('scheduled games do not confuse season records or ranking with scores',()=>{const [g]=parseMaxPreps(card(),sport,date).games;assert.deepEqual(g.teams.map(t=>t.score),[null,null]);assert.equal(g.teams[0].name,'Alcorn Central');assert.equal(g.startLabel,'5:30 PM');assert.equal(g.status,'scheduled');});
test('final scores retain team orientation and zero scores',()=>{const [g]=parseMaxPreps(card({scores:[0,3],detail:'Final',state:'boxscore'}),sport,date).games;assert.deepEqual(g.teams.map(t=>t.score),[0,3]);assert.equal(g.status,'final');});
test('live games require an explicit source live flag',()=>{const [g]=parseMaxPreps(card({scores:[1,2],detail:'Set 4',state:'live',live:'1'}),sport,date).games;assert.equal(g.status,'live');assert.equal(g.detail,'Set 4');});
test('in-progress contests without a submitted score remain live with unknown scores',()=>{const [g]=parseMaxPreps(card({detail:'In progress',state:'contest-in-progress',live:'0'}),sport,date).games;assert.equal(g.status,'live');assert.deepEqual(g.teams.map(t=>t.score),[null,null]);});
test('next-day redirects and unrelated national cards cannot become today’s games',()=>{const html=card({path:'/ms/volleyball/match/a-vs-b/10-8-2026/'})+card({id:'b',path:'/tx/volleyball/match/a-vs-b/10-6-2026/'})+card({id:'c'}).replace('data-contest-id','data-contest-id-x');const r=parseMaxPreps(html,sport,date);assert.equal(r.games.length,0);assert.equal(r.skippedDate,1);assert.equal(r.excludedState,1);});
test('Mississippi interstate games are included; provider blocks fail visibly',()=>{assert.equal(parseMaxPreps(card({path:'/inter-state/volleyball/match/corinth-ms-vs-selmer-tn/10-6-2026/'}),sport,date).games.length,1);assert.throws(()=>parseMaxPreps('<html>Access denied</html>',sport,date));});
test('county filtering includes either school and does not restrict sports',()=>{const games=[...parseMaxPreps(card(),sport,date).games,...parseMaxPreps(card({id:'b',names:['Ripley','Oxford']}),{...sport,key:'basketball',label:'Boys Basketball'},date).games];assert.equal(filterGames(games,{group:'alcorn'}).length,1);assert.equal(filterGames(games,{group:'tippah'})[0].sport,'Boys Basketball');assert.equal(filterGames(games,{group:'custom',teams:[]}).length,0);assert.equal(filterGames(games,{group:'custom',teams:['Kossuth']}).length,1);});
test('Central date handles midnight and daylight saving correctly',()=>{assert.equal(centralDate('2026-10-07T04:59:59Z'),'2026-10-06');assert.equal(centralDate('2026-10-07T05:00:00Z'),'2026-10-07');assert.equal(centralDate('2026-12-07T05:30:00Z'),'2026-12-06');assert.equal(validDate('2026-02-30'),false);});
test('duplicate contest cards keep a final score over an earlier schedule',()=>{const games=deduplicate([...parseMaxPreps(card(),sport,date).games,...parseMaxPreps(card({scores:[0,3],detail:'Final',state:'boxscore'}),sport,date).games]);assert.equal(games.length,1);assert.equal(games[0].status,'final');assert.deepEqual(games[0].teams.map(t=>t.score),[0,3]);});
test('source requests are shared and outage data expires rather than claiming live scores forever',async()=>{let now=100000,calls=0,fail=false;const c=new FeedCollector({now:()=>now,spacingMs:0,fetchImpl:async()=>{calls++;if(fail)throw Error('Offline');return new Response('ok');}});const parse=()=>({games:[{status:'live'}]});const [a,b]=await Promise.all([c.read('test','https://example.com',parse,1000),c.read('test','https://example.com',parse,1000)]);assert.equal(calls,1);assert.deepEqual(a,b);await c.read('test','https://example.com',parse,1000);assert.equal(calls,1);now+=2000;fail=true;const stale=await c.read('test','https://example.com',parse,1000);assert.equal(stale.stale,true);assert.equal(stale.data.games.length,1);now+=3600001;const empty=await c.read('test','https://example.com',parse,1000);assert.deepEqual(empty.data.games,[]);});

test('DeSoto preset includes either public or private school without matching unrelated counties',()=>{const games=[...parseMaxPreps(card({id:'d1',names:['Oxford','DeSoto Central']}),sport,date).games,...parseMaxPreps(card({id:'d2',names:['DeSoto Christian Academy','Corinth']}),sport,date).games,...parseMaxPreps(card({id:'d3',names:['Ripley','Kossuth']}),sport,date).games];assert.deepEqual(filterGames(games,{group:'desoto'}).map(g=>g.contestId),['d1','d2']);});
